spring:
  profiles:
    active: local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database: mysql
  datasource:
    url: ${JDBC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jackson:
    property-naming-strategy: SNAKE_CASE
  lifecycle:
    timeout-per-shutdown-phase: 20s
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
auth:
  jwt:
    exp:
      refresh: ${JWT_EXP_REFRESH}
      access: ${JWT_EXP_ACCESS}
    secret: ${JWT_SECRET_KEY}
server:
  servlet:
    context-path: /v1
  shutdown: graceful
cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_KEY}
      secretKey: ${AWS_S3_SECRET}
    s3:
      bucket: s3-jobits
      host: ${S3_HOST_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false